model_params:
  encoder_depth: 1
  encoder_units: 1
  decoder_depth: 1
  embedding_dim: 10

tf_dataset_params:
  batch_size: 32
  buffer_size: 1000
  reverse_context: True

training_params:
  epochs: 1