model_params:
  depth: 2
  encoder_units: 256 
  embedding_dim: None
  use_embedding_layer: False
  batch_size: 64
  encoder_input_shape: [128, 300]
  decoder_input_shape: [129, 300]


tf_dataset_params:
  batch_size: 64
  buffer_size: 10000
  reverse_context: True

training_params:
  epochs: 10