model_params:
  encoder_depth: 1
  encoder_units: 512 
  decoder_depth: 1
  embedding_dim: 128

tf_dataset_params:
  batch_size: 32
  buffer_size: 10000
  reverse_context: True

training_params:
  epochs: 10