model_params:
  depth: 2
  n_units: 128


tf_dataset_params:
  batch_size: 32
  buffer_size: 10000
  reverse_context: True
  vocab_size: 20000
  x_max_length: 50
  y_max_length: 50

training_params:
  epochs: 10